### ISSUE TITLE
KeyError: 'center_weight'

### ISSUE THREAD

**Issue by LYL-hub-source** [Zheng222/DMFN#19]
@Zheng222 
Hello, when I run the train.py file, the following error occurs, may I ask how to solve this? Thank you !

Number of training images: 400, iters: 40
Total epochs needed: 3 for iters 100
Number of val images in [DH]: 100
Loading pretrained model for G [outputs/celebahq-regular/checkpoints/latest_G.pth] ...
Traceback (most recent call last):
  File "D:/Project/Py_Project/image-inpainting/FG/DMFN-master/train.py", line 49, in <module>
    model = InpaintingModel(config)
  File "D:\Project\Py_Project\image-inpainting\FG\DMFN-master\models\inpainting_model.py", line 84, in __init__
    if train_opt['center_weight'] > 0:
KeyError: 'center_weight'

Process finished with exit code 1

**Comment by Zheng222** [comment]
@LYL-hub-source Hello, I have fixed this issue in the `config/celeba-hq-regular_list.yaml`.

**Comment by LYL-hub-source** [comment]
@Zheng222   Thank you, very much. The problem was solved.
