### ISSUE TITLE
test_issues

### ISSUE THREAD

**Issue by LYL-hub-source** [Zheng222/DMFN#20]
@Zheng222 
Sorry to bother you again. When I test my image, I get the following error, a little confused, the path seems to be ok. Thank you very much!

Loading the checkpoint for G [outputs/DH_train/celeba-hq-regular/checkpoints/latest_G.pth] ...
Number of test images in [DH]: 100
Traceback (most recent call last):
  File "D:/Project/Py_Project/image-inpainting/FG/DMFN-master/test.py", line 60, in <module>
    _write_images(visual_images, 1, '%s/%s' % (opts.output_folder, img_paths[0].split('/')[-1]))
  File "D:\Project\Py_Project\image-inpainting\FG\DMFN-master\utils.py", line 15, in _write_images
    vutils.save_image(image_grid, file_name, nrow=1)
  File "F:\Download\Anaconda\envs\Pytorch\lib\site-packages\torchvision\utils.py", line 105, in save_image
    im.save(filename)
  File "F:\Download\Anaconda\envs\Pytorch\lib\site-packages\PIL\Image.py", line 2237, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'outputs/DH_train/celeba-hq-regular/images/D:\\Project\\Py_Project\\image-inpainting\\FG\\DMFN-master\\DunHuang_data\\train_GT\\401.jpg'

**Comment by LYL-hub-source** [comment]
@Zheng222 
Hello,when I exchanged the path about '--config' , '--output_folder', and 'checkpoint' , but the code is not run successfuly.  How can I do to run the test code.  Thank you very much!

**Comment by ifigs** [comment]
Turns out the paths in the yaml file aren't correct! You'll have to get some of the paths to match as well as the name of the model to be used.
